language: node_js
node_js:
  - "10"

install:
  - npm install

script:
  - npm run lint && node_modules/.bin/nyc --reporter=lcov --reporter=text-lcov npm test

after_script:
  - "cat ./coverage/lcov.info | ./node_modules/.bin/coveralls"
